uiWidth: 700
uiHeight: 700
debug: true
numberOfRandomParticles: 500
universeConfig:
  ticksPerSecond: 60
  width: 2000
  height: 2000
  gravitationalAcceleration: 9806.65
  coefficientOfRestitution: 0.9
  minimumDiameter: 30
  updatesPerTick: 200
  debug: true
  detectorType: SORTED
  resolverType: EXPONENTIAL
  borderHandlerType: exponential
  particleGroupHandlerType: exponential



